[build-system]
requires = ["setuptools>=61.0", "pydantic>=2.13.4"]
build-backend = "setuptools.build_meta"

[project]
name = "response-body-issue"
version = "0.1.0"
description = "library of standardized HTTP response bodies."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
authors = [
    { name = "Matoshix", email = "maksimpest7@gmail.com" }
]
dependencies = [
    "pydantic>=2.13.4"
]

